version: "3.9"
services:
    forkify-au:
        image: gimmitest/forkify-au
        build:
            context: auth
            dockerfile: Dockerfile
            args:
                DEFAULT_PORT: 8080
        container_name: ff-au
        env_file: auth/.env
        extends:
            file: docker-compose-base.yaml
            service: forkify-au-base
    forkify-be:
        image: gimmitest/forkify-be
        build:
            context: backend
            dockerfile: Dockerfile
            args:
                DEFAULT_PORT: 8000
        container_name: ff-be
        environment:
            - AUTH_PORT=8080
            - SERVER_HOST=ff-au
        env_file: backend/.env
        extends:
            file: docker-compose-base.yaml
            service: forkify-be-base
        depends_on:
            - forkify-au
    forkify-fe:
        image: gimmitest/forkify-fe
        build:
            context: frontend
            dockerfile: Dockerfile
            args:
                DEFAULT_PORT: 80
        container_name: ff-fe
        environment:
            BACKEND_PORT: 8000
        extends:
            file: docker-compose-base.yaml
            service: forkify-fe-base
        depends_on:
            - forkify-be
volumes:
    be-logs:
networks:
    forkify-net:
