version: "3.8"
services:
    forkify-be:
        image: gimmitest/forkify-be
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: ff-be
        ports:
            - 8000:8000
    forkify-fe:
        image: gimmitest/forkify-fe
        build:
            context: frontend
            dockerfile: Dockerfile
        container_name: ff-fe
        ports:
            - 6768:80
        depends_on:
            - forkify-be
