apiVersion: v1
kind: Service
metadata:
    name: forkify-be-svc
spec:
    selector:
        app: backend
    ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
    type: NodePort
