apiVersion: apps/v1
kind: Deployment
metadata:
    name: forkify-fe-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: ff-fe
                  image: gimmitest/forkify-fe
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  env:
                      - name: BACKEND_PORT
                        value: "54593" #cambiare ad ogni lancio di minikube service
