apiVersion: v1
kind: Service
metadata:
    name: forkify-fe-svc
spec:
    selector:
        app: frontend
    ports:
        - port: 6768
          targetPort: 80
          protocol: TCP
    type: NodePort
