apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: forkify-pvc
spec:
    volumeName: forkify-pv
    accessModes:
        - ReadWriteOnce
    storageClassName: standard
    resources:
        requests:
            storage: 1Gi
