apiVersion: v1
kind: Service
metadata:
    name: forkify-fe-svc
spec:
    selector:
        app: frontend
    ports:
        - port: 6768
          targetPort: 80
          protocol: TCP
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: forkify-be-svc
spec:
    selector:
        app: backend
    ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: forkify-au-svc
spec:
    selector:
        app: auth
    ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
    type: ClusterIP
